- name: Deploy Six Cities
  hosts: all
  become: yes
  
  tasks:

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    
    - name: Copy Production Dist
      ansible.builtin.copy:
        src: ~/2345789-six-cities-4/dist.tar.gz
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

    - name: Copy Nginx Config
      ansible.builtin.copy:
        src: ~/2345789-six-cities-4/deploy/six-cities.conf
        dest: /etc/nginx/sites-enabled/
        owner: root
        group: root
        mode: '0644'

    - name: Unpack Dist
      ansible.builtin.shell:
        chdir: /var/www/html/
        cmd: "rm -rf assets/ css/ fonts/ img/ && tar -xzf dist.tar.gz --warning=no-unknown-keyword && mv ./dist/* . && rm -rf dist/ && rm dist.tar.gz"

    - name: Restart Nginx
      ansible.builtin.shell:
        cmd: "systemctl restart nginx" 
      